### PR TITLE
Some modifications

### PR DESCRIPTION
**Pull request by fchareyron**

### CODE REVIEW

**Comment by fchareyron** [comment]
Please check these modifications.

**Comment by goodboy** [comment]
@fchareyron so to clarify, you need to make the pull request against the master branch of the [SIPp/pysipp](https://github.com/SIPp/pysipp) project **not your fork** of the project.
In other words, the merge you've done here does not actually bring you changes into the main project.

Take a look at this tutorial for tips; particularly **step 7**:
http://www.codenewbie.org/blogs/how-to-make-a-pull-request

These might also provide insight.
https://help.github.com/articles/creating-a-pull-request/
https://github.com/blog/1943-how-to-write-the-perfect-pull-request

**Comment by fchareyron** [comment]
No way to push modifications in git, permission deny.

What account should I use?

Regards

Frederic

**Comment by goodboy** [comment]
@fchareyron I think you're misunderstanding. You **do** push your changes using git to **this forked repo** but you make the pull request (using Github's web interface) from the master branch of this repo against the [upstream repo](https://github.com/SIPp/pysipp).

Please have a look at some of the tutorials I posted or spend some time reading up on the on how to make PRs for other projects on github.

This issue might help explain it:
http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request

**Pull request merged**
